# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
  FACEBOOK_KEY: '222471321637574'
  FACEBOOK_SECRET: '67b1d99b6964f65bf9f1c8af54937c61'
  callback url: '0.0.0.0:3000/users/sign_up'

  GOOGLE_STORAGE_ACCESS_KEY_ID: 'GOOG3ARSE5KERW77L5HXTRCM'
  GOOGLE_STORAGE_SECRET_ACCESS_KEY: '5AYcx3vQuEdIqKG2sKM1RBhLWPRIR0DUYNBsMesQ'

test:
  GOOGLE_STORAGE_ACCESS_KEY_ID: 'GOOG3ARSE5KERW77L5HXTRCM'
  GOOGLE_STORAGE_SECRET_ACCESS_KEY: '5AYcx3vQuEdIqKG2sKM1RBhLWPRIR0DUYNBsMesQ'

production:
  FACEBOOK_KEY: '222471321637574'
  FACEBOOK_SECRET: '67b1d99b6964f65bf9f1c8af54937c61'
  callback url: '#'

  GOOGLE_STORAGE_ACCESS_KEY_ID: 'GOOG3ARSE5KERW77L5HXTRCM'
  GOOGLE_STORAGE_SECRET_ACCESS_KEY: '5AYcx3vQuEdIqKG2sKM1RBhLWPRIR0DUYNBsMesQ'